Metrics/LineLength:
  Max: 80

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/RegexpLiteral:
  EnforcedStyle: slashes

  SupportedStyles:
    - slashes
    - percent_r
    - mixed

  AllowInnerSlashes: true

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Lint/ImplicitStringConcatenation:
  Enabled: false

AllCops:
  Exclude:
    - './examples'
    - './spec/spec_helper.rb'

